#! /bin/bash

echo ' '
read -p 'Would you like to clear the previous map database? (y/n): ' ansinput

if [ “$ansinput” = “y” ]
then
 printf '\n Map deleted \n'
 rm -f ~/.ros/rtabmap.db

elif [ “$ansinput” = “n” ]
then
 printf '\n Map kept \n'

else
 echo 'Warning: Not an acceptable option. Choose (y/n).
         '
fi

echo ' '

read -p 'Choose target world (1: kitchen_dining, 2: bot_cafe) : ' input_choice

if [ “$input_choice” = “2” ]
then
 xterm -e roslaunch slam_project world.launch world_file:=/home/shingo/work/RoboND-MayMyWorld-Project/catkin_ws/src/slam_project/worlds/bot_cafe.world &
else
 xterm -e roslaunch slam_project world.launch world_file:=/home/shingo/work/RoboND-MayMyWorld-Project/catkin_ws/src/slam_project/worlds/kitchen_dining.world &
fi

sleep 3

xterm -e roslaunch slam_project teleop.launch &

sleep 3

echo ' '
read -p 'Press any key to continue to mapping... ' -n1 -s

xterm -e roslaunch slam_project mapping.launch simulation:=true &

sleep 3 &&

xterm -e roslaunch slam_project rviz.launch

echo ' '
echo 'Script Completed'
echo ' '
